### ISSUE TITLE
Heroku deployment issue

### ISSUE THREAD

**Issue by X3NOSIZ** [onderonur/bubbly#1]
Hi Onur! I am a high school student and I am making a socket-based Node app based on React and Express. I am highly inspired from your project. I git cloned this repo on my local and followed the same steps that you mentioned in the README.md file. I am using VSCode on Windows. The app is running perfectly fine on my local. But when I try to deploy this app to Heroku, keeping everything as default directly from the cmd line terminal, the app deployment fails. The build of heroku breaks at this stage - 

```

       > api@1.0.0 build /tmp/build_88b6803f5489844527c4052de36e76b4/api

       > tsc

       
sh: 1: tsc: not found

npm ERR! code ELIFECYCLE

npm ERR! syscall spawn

npm ERR! file sh

npm ERR! errno ENOENT

npm ERR! api@1.0.0 build: `tsc`

npm ERR! spawn ENOENT

npm ERR! 

npm ERR! Failed at the api@1.0.0 build script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /tmp/npmcache.KLhiS/_logs/2020-07-05T17_59_27_385Z-debug.log

npm ERR! code ELIFECYCLE

npm ERR! errno 1
```

Can you please help me fix this issue?
Thanks :)

**Comment by onderonur** [comment]
Hi!

So, the problem is, TypeScript is a devDependency and Heroku doesn't install devDependencies by default.
TypeScript is not needed to run the project, but it must be installed to build the project. I may place TypeScript in regular dependencies, but I'm not sure if that would be a valid solution.
Anyway, to install devDependencies on Heroku, you need to set `NPM_CONFIG_PRODUCTION` env variable as `false` in your heroku project settings. You can also put this variable in a `.env` file etc.
After trying this, if you share the result, I can close this issue :)

Thanks!

**Comment by X3NOSIZ** [comment]
Thanks for the quick reply @onderonur :)
Much appreciated 😃

**Comment by X3NOSIZ** [comment]
Well I did set `NPM_CONFIG_PRODUCTION=false` inside the api/.env file, but again I am facing build issues.

The whole process includes, 
1. Git clone your repo in my local
2. Kept everything as it is on default.
3. `cd api => npm install` & `cd client => npm install` (installed node modules in subsequent directories)
4. Generated a secret key using `node => require('crypto').randomBytes(64).toString('hex')` and pasted that inside api/.env as `JWT_TOKEN_SECRET=**"key"** ` as mentioned on README.md
5. At this point the app is running perfectly by doing `npm run dev` on `/api` & `npm start` on `/client`. Then I did npm run build, which did produce an optimized production react build.
6. Added `NPM_CONFIG_PRODUCTION=false` in `/api/.env`
7. Git init
8. Git add .
9. .......  (Followed normal deployment method after logging into heroku)
10. git push heroku master

But deployment fails everytime :(

**Comment by X3NOSIZ** [comment]
@onderonur Any idea why this is getting failed? Also I searched over stackoverflow and github issues, some mentioned to change the build command in `api/package.json` as `"build": "tsc @tscfiles || echo done"` which I did, but this also didn't worked! :(

**Comment by onderonur** [comment]
@X3NOSIZ Hi again,
First of all just to clarify, `build` script is not executed on Heroku. Because there is a `heroku-postbuild` script in `package.json`, Heroku runs it and ignores `build` script. You can use `build` for other deployment environments, or to test it locally.
It runs `npm install` first. Then runs `heroku-postbuild`. It installs packages for api and client. After that, project builds. 
Can you copy-paste your deployment error logs, so I will try to help you.
Sorry if I forgot to add something in `README.md`:)
I surely want to help.

**Comment by X3NOSIZ** [comment]
Yeah sure, this was the deployment error log of Heroku

```


-----> Node.js app detected

       

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NODE_ENV=production

       NODE_MODULES_CACHE=true

       NODE_VERBOSE=false

       

-----> Installing binaries

       engines.node (package.json):  unspecified

       engines.npm (package.json):   unspecified (use default)

       

       Resolving node version 12.x...

       Downloading and installing node 12.18.2...

       Using default npm version: 6.14.5

       

-----> Installing dependencies

       Installing node modules (package.json + package-lock)

       added 12 packages from 4 contributors and audited 12 packages in 0.559s

       

       2 packages are looking for funding

         run `npm fund` for details

       

       found 0 vulnerabilities

       

       

-----> Build

       Detected both "build" and "heroku-postbuild" scripts

       Running heroku-postbuild

       

       > bubbly@1.0.0 heroku-postbuild /tmp/build_88b6803f5489844527c4052de36e76b4

       > npm run install:api && npm run install:client && npm run build

       

       

       > bubbly@1.0.0 install:api /tmp/build_88b6803f5489844527c4052de36e76b4

       > cd api && npm install

       

       added 132 packages from 85 contributors and audited 386 packages in 4.618s

       

       1 package is looking for funding

         run `npm fund` for details

       

       found 5 low severity vulnerabilities

         run `npm audit fix` to fix them, or `npm audit` for details

       

       > bubbly@1.0.0 install:client /tmp/build_88b6803f5489844527c4052de36e76b4

       > cd client && npm install

       

       audited 12 packages in 0.348s

       

       2 packages are looking for funding

         run `npm fund` for details

       

       found 0 vulnerabilities

       

       

       > bubbly@1.0.0 build /tmp/build_88b6803f5489844527c4052de36e76b4

       > npm run build:api && npm run build:client

       

       

       > bubbly@1.0.0 build:api /tmp/build_88b6803f5489844527c4052de36e76b4

       > cd api && npm run build

       

       

       > api@1.0.0 build /tmp/build_88b6803f5489844527c4052de36e76b4/api

       > tsc

       

sh: 1: tsc: not found

npm ERR! code ELIFECYCLE

npm ERR! syscall spawn

npm ERR! file sh

npm ERR! errno ENOENT

npm ERR! api@1.0.0 build: `tsc`

npm ERR! spawn ENOENT

npm ERR! 

npm ERR! Failed at the api@1.0.0 build script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /tmp/npmcache.KLhiS/_logs/2020-07-05T17_59_27_385Z-debug.log

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! bubbly@1.0.0 build:api: `cd api && npm run build`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the bubbly@1.0.0 build:api script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /tmp/npmcache.KLhiS/_logs/2020-07-05T17_59_27_396Z-debug.log

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! bubbly@1.0.0 build: `npm run build:api && npm run build:client`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the bubbly@1.0.0 build script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /tmp/npmcache.KLhiS/_logs/2020-07-05T17_59_27_410Z-debug.log

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! bubbly@1.0.0 heroku-postbuild: `npm run install:api && npm run install:client && npm run build`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the bubbly@1.0.0 heroku-postbuild script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /tmp/npmcache.KLhiS/_logs/2020-07-05T17_59_27_421Z-debug.log

-----> Build failed

       

       We're sorry this build is failing! You can troubleshoot common issues here:

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       

       Some possible problems:

       

       - Node version not specified in package.json

         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

       

       Love,

       Heroku

       

 !     Push rejected, failed to compile Node.js app.

 !     Push failed
```

**Comment by onderonur** [comment]
@X3NOSIZ  I think the problem might be that setting `NPM_CONFIG_PRODUCTION` in `api/.env` file. I think you should set this value at the root of the project.
Here is how I do it:
* Go to your project settings: https://dashboard.heroku.com/apps/YOUR_APP_NAME/settings
* Go to **Config Vars** section
* Click **Reveal Config Vars**
* Add `NPM_CONFIG_PRODUCTION` as `false`
* Run deployment again

I hope this will solve the problem. Because it still can't find TypeScript when building the api.
